remote_theme: tedivm/jekyll-theme-portfolio
title: kahqgc's homepage
description: Bookmark this to keep an eye on my project updates!
url: "https://kahqgc.github.io"
baseurl: ""

github_username: kahqgc

plugins:
  - jekyll-remote-theme
  - jekyll-feed

