theme: jekyll-theme-minimal
title: kahqgc's homepage
description: Bookmark this to keep an eye on my project updates!

github_username: kahqgc

nav:
  - title: Home
    url: /
  - title: Resume
    url: /resume-and-achievements/
  - title: Project Work
    url: /project-work/
  - title: Contact
    url: /contact/
